# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc

# IP: C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet

# IP: C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_ram || ORIG_REF_NAME==axi_ram} -quiet] -quiet

# IP: C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_crossbar_1x2 || ORIG_REF_NAME==axi_crossbar_1x2} -quiet] -quiet
