# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/project/loongson.cache/wt [current_project]
set_property parent.project_path C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/project/loongson.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/project/loongson.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/func/obj/inst_ram.coe
read_verilog C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/mycpu.vh
read_verilog -library xil_defaultlib {
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/alu.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/axi_wrap/axi_wrap.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/ram_wrap/axi_wrap_ram.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/CONFREG/confreg.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/csr_regfile.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/decoder_2_4.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/decoder_4_16.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/decoder_5_32.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/decoder_6_64.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/exe_stage.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/id_stage.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/if_stage.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/mem_stage.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/mycpu_top.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/regfile.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/tlb.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/myCPU/wb_stage.v
  C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/soc_lite_top.v
}
read_ip -quiet C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all c:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc
set_property used_in_implementation false [get_files C:/Users/kl42c/Documents/GitHub/Ourcpu/output/exp19/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_lite_top -part xc7a200tfbg676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
